name = "rd-public"
compatibility_date = "2025-01-01"

routes = [
  { pattern = "roguedivisions.com/thesis/*", zone_name = "roguedivisions.com" },
  { pattern = "roguedivisions.com/methodology/*", zone_name = "roguedivisions.com" },
]

[assets]
directory = "./public"
not_found_handling = "404-page"
